In [1]:
import pandas as pd
import numpy as np
# from sklearn.model_selection import train_test_split

In [2]:
df_leitura = pd.read_csv('dengue_sinan.csv')

C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\3565713140.py:1: DtypeWarning: Columns (30,31,53,54,55,59,61,63,65,71,83,89,100,116,131,137) have mixed types. Specify dtype option on import or set low_memory=False.
  df_leitura = pd.read_csv('dengue_sinan.csv')

In [3]:
df = df_leitura

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620211 entries, 0 to 620210
Columns: 148 entries, NU_NOTIFIC to ID_CNS_SUS_HASHED
dtypes: float64(115), int64(8), object(25)
memory usage: 700.3+ MB

In [5]:
campos_obrigatorios = [
    'ID_AGRAVO', 'DT_INVEST', 'FEBRE', 'MIALGIA', 'CEFALEIA', 'EXANTEMA',
    'VOMITO', 'NAUSEA', 'DOR_COSTAS', 'CONJUNTVIT', 'ARTRITE', 'ARTRALGIA', 'PETEQUIA_N',
    'LEUCOPENIA', 'LACO', 'DOR_RETRO', 'DIABETES', 'HEMATOLOG', 'HEPATOPAT', 'RENAL',
    'HIPERTENSA', 'ACIDO_PEPT', 'AUTO_IMUNE'
]

In [6]:
#Removendo valores vazios/null

df.dropna(subset=campos_obrigatorios, inplace=True)

In [7]:
campos_obrigatorios_12 = [
    'FEBRE', 'MIALGIA', 'CEFALEIA', 'EXANTEMA',
    'VOMITO', 'NAUSEA', 'DOR_COSTAS', 'CONJUNTVIT', 'ARTRITE', 'ARTRALGIA', 'PETEQUIA_N',
    'LEUCOPENIA', 'LACO', 'DOR_RETRO', 'DIABETES', 'HEMATOLOG', 'HEPATOPAT', 'RENAL',
    'HIPERTENSA', 'ACIDO_PEPT', 'AUTO_IMUNE'
]

In [8]:
def process_campos_obrigatorios(df, columns):
    for column in columns:
        if column in df.columns:
            df = df.dropna(subset=[column])
            df = df[df[column].isin([1, 2])]
    return df

In [9]:
df = df[df['FEBRE'].isin([1, 2])]

In [10]:
df = process_campos_obrigatorios(df, campos_obrigatorios_12)

In [11]:
df = df[pd.to_numeric(df['CLASSI_FIN'], errors='coerce').notna() | df['CLASSI_FIN'].isna()]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 540724 entries, 2 to 615873
Columns: 148 entries, NU_NOTIFIC to ID_CNS_SUS_HASHED
dtypes: float64(115), int64(8), object(25)
memory usage: 614.7+ MB

In [13]:
# SOROTIPO: Obrigat√≥rio Se campo 'RESUL_VI_N' ou campo 'RESUL_PCR_'= 1.
# Campo desabilitado se campo 'RESUL_VI_N' e campo 'RESUL_PCR_' diferente de 1.
# Habilitado apenas se campo 'ID_AGRAVO' = 1

df_sorotipo =  df[~(((df['RESUL_VI_N'] == 1) | (df['RESUL_PCR_'] == 1)) & df['SOROTIPO'].isna())]
df_sorotipo = df_sorotipo[~((df_sorotipo['SOROTIPO'].notna()) & (df_sorotipo['RESUL_VI_N'] != 1) & (df_sorotipo['RESUL_PCR_'] != 1))]

In [14]:
df_sorotipo

,NU_NOTIFIC,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,...,DT_TRANSRM,DT_TRANSRS,DT_TRANSSE,NU_LOTE_V,NU_LOTE_H,CS_FLXRET,FLXRECEBI,IDENT_MICR,MIGRADO_W,ID_CNS_SUS_HASHED
2,5082,2,A90,2016-03-25,201612,2016,29,293250,1385.0,2800527.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,e0f037bc45eeea73df919230256055724a0bc45b990d62...
5,22144,2,A90,2016-06-30,201626,2016,29,290460,1398.0,5075076.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
6,501,2,A90,2016-03-07,201610,2016,29,291560,1388.0,2414155.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
9,12379,2,A90,2016-01-08,201601,2016,29,291810,1393.0,2483114.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,56ba9de049836e4fa21d8a918fd7d8a6a9e69b23d5b64a...
10,2564,2,A90,2016-01-05,201601,2016,29,290560,1385.0,2771195.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,246037760bf67d1c246b8dd02298b9487c7b9b5f87f6c3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615867,1192024,2,A90,2024-02-21,202408,2024,29,292180,1398.0,2557088.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,a089fe3388d4442a5fa5e7af093309bdbbe37ee4b994b9...
615868,160858,2,A90,2024-03-03,202410,2024,29,290320,1403.0,2659069.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,0594aea8d62c0773c69b88ef616f567697270072351d82...
615869,16943,2,A90,2024-02-29,202409,2024,29,291640,1398.0,3791378.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,e98869669baa7aa8bf45ea57231a0abe0dd343361ec04d...
615870,374884,2,A90,2024-02-07,202406,2024,29,292740,1380.0,2389746.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
615873,29,2,A90,2024-03-01,202409,2024,29,292550,1388.0,7126816.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,87eaab98ce59a89ded63e587cb418249e7e6ac64b146c2...

In [15]:
# CLASSI_FIN: Campo Obrigat√≥rio quando o campo 'DT_ENCERRA' estiver preenchido.
# Desabilitar categoria 13 se campo 'ID_AGRAVO'= 1.
# Desabilitar categorias 10, 11 e 12 se campo 'ID_AGRAVO'=2

df_classifin = df_sorotipo[~(df_sorotipo['DT_ENCERRA'].notna() & df_sorotipo['CLASSI_FIN'].isna())]
df_classifin = df_classifin[~((df_classifin['ID_AGRAVO'] == 1) & (df_classifin['CLASSI_FIN'] == 13))]
df_classifin = df_classifin[~((df_classifin['ID_AGRAVO'] == 2) & (df_classifin['CLASSI_FIN'].isin([10, 11, 12])))]

In [16]:
# CLINIC_CHIK: Campo Obrigat√≥rio
# Se campo 'CLASSI_FIN'=13 e se campo 'CRITERIO'= 1 ou 2

df_clinicchik = df_classifin[~((df_classifin['CLASSI_FIN'] == 13) & (df_classifin['CRITERIO'].isin([1, 2])) & df_classifin['CLINC_CHIK'].isna())]

In [17]:
# DT_OBITO: Campo Obrigat√≥rio se 'EVOLUCAO'=2 ou 3 ou 4.
# Data deve ser maior ou igual a 'DT_ALRM'.

df_dtobito= df_clinicchik[~(((df_clinicchik['EVOLUCAO'].isin([2, 3, 4])) & (df_clinicchik['DT_OBITO'].isna() | (df_clinicchik['DT_OBITO'] < df_clinicchik['DT_ALRM']))))]
df_dtobito

,NU_NOTIFIC,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,...,DT_TRANSRM,DT_TRANSRS,DT_TRANSSE,NU_LOTE_V,NU_LOTE_H,CS_FLXRET,FLXRECEBI,IDENT_MICR,MIGRADO_W,ID_CNS_SUS_HASHED
2,5082,2,A90,2016-03-25,201612,2016,29,293250,1385.0,2800527.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,e0f037bc45eeea73df919230256055724a0bc45b990d62...
5,22144,2,A90,2016-06-30,201626,2016,29,290460,1398.0,5075076.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
6,501,2,A90,2016-03-07,201610,2016,29,291560,1388.0,2414155.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
9,12379,2,A90,2016-01-08,201601,2016,29,291810,1393.0,2483114.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,56ba9de049836e4fa21d8a918fd7d8a6a9e69b23d5b64a...
10,2564,2,A90,2016-01-05,201601,2016,29,290560,1385.0,2771195.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,246037760bf67d1c246b8dd02298b9487c7b9b5f87f6c3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615867,1192024,2,A90,2024-02-21,202408,2024,29,292180,1398.0,2557088.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,a089fe3388d4442a5fa5e7af093309bdbbe37ee4b994b9...
615868,160858,2,A90,2024-03-03,202410,2024,29,290320,1403.0,2659069.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,0594aea8d62c0773c69b88ef616f567697270072351d82...
615869,16943,2,A90,2024-02-29,202409,2024,29,291640,1398.0,3791378.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,e98869669baa7aa8bf45ea57231a0abe0dd343361ec04d...
615870,374884,2,A90,2024-02-07,202406,2024,29,292740,1380.0,2389746.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
615873,29,2,A90,2024-03-01,202409,2024,29,292550,1388.0,7126816.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,87eaab98ce59a89ded63e587cb418249e7e6ac64b146c2...

In [18]:
#DT_ENCERRA: Campo Obrigat√≥rio quando campo 'CLASSI_FIN' estiver preenchido E o campo 'CRITERIO' for diferente de 3.
# Campo desabilitado se o campo 'CRITERIO' for igual a 3.

df_dtobito['DT_ENCERRA'] = pd.to_datetime(df_dtobito['DT_ENCERRA'], errors='coerce')
df_encerra = df_dtobito[~((df_dtobito['CLASSI_FIN'].notna()) & (df_dtobito['CRITERIO'] != 3) & df_dtobito['DT_ENCERRA'].isna())]
df_encerra = df_encerra[~((df_encerra['CRITERIO'] == 3) & df_encerra['DT_ENCERRA'].notna())]

df_encerra

C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1807633503.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dtobito['DT_ENCERRA'] = pd.to_datetime(df_dtobito['DT_ENCERRA'], errors='coerce')

,NU_NOTIFIC,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,...,DT_TRANSRM,DT_TRANSRS,DT_TRANSSE,NU_LOTE_V,NU_LOTE_H,CS_FLXRET,FLXRECEBI,IDENT_MICR,MIGRADO_W,ID_CNS_SUS_HASHED
2,5082,2,A90,2016-03-25,201612,2016,29,293250,1385.0,2800527.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,e0f037bc45eeea73df919230256055724a0bc45b990d62...
5,22144,2,A90,2016-06-30,201626,2016,29,290460,1398.0,5075076.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
6,501,2,A90,2016-03-07,201610,2016,29,291560,1388.0,2414155.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
9,12379,2,A90,2016-01-08,201601,2016,29,291810,1393.0,2483114.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,56ba9de049836e4fa21d8a918fd7d8a6a9e69b23d5b64a...
10,2564,2,A90,2016-01-05,201601,2016,29,290560,1385.0,2771195.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,246037760bf67d1c246b8dd02298b9487c7b9b5f87f6c3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615867,1192024,2,A90,2024-02-21,202408,2024,29,292180,1398.0,2557088.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,a089fe3388d4442a5fa5e7af093309bdbbe37ee4b994b9...
615868,160858,2,A90,2024-03-03,202410,2024,29,290320,1403.0,2659069.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,0594aea8d62c0773c69b88ef616f567697270072351d82...
615869,16943,2,A90,2024-02-29,202409,2024,29,291640,1398.0,3791378.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,e98869669baa7aa8bf45ea57231a0abe0dd343361ec04d...
615870,374884,2,A90,2024-02-07,202406,2024,29,292740,1380.0,2389746.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
615873,29,2,A90,2024-03-01,202409,2024,29,292550,1388.0,7126816.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,87eaab98ce59a89ded63e587cb418249e7e6ac64b146c2...

In [19]:
def alrm_condicional(df):
    # Condi√ß√µes para os campos obrigat√≥rios
    mandatory_conditions = (df['CLASSI_FIN'].isin([11, 12]) & df['CRITERIO'].isin([1, 2]))

    # Lista de campos a serem verificados
    fields = ['ALRM_SANG', 'ALRM_HEMAT', 'ALRM_HEPAT', 'ALRM_LIQ', 'ALRM_LETAR', 'ALRM_ABDOM', 'ALRM_VOM', 'ALRM_PLAQ', 'ALRM_HIPOT', 'DT_ALRM']

    for field in fields:
        # Remover linhas onde o campo √© obrigat√≥rio mas est√° nulo
        df = df[~(mandatory_conditions & df[field].isna())]
        # Remover linhas onde o campo est√° preenchido mas a condi√ß√£o n√£o √© satisfeita
        df = df[~((~mandatory_conditions) & df[field].notna())]

    return df

In [20]:
df_almr = alrm_condicional(df_encerra)
df_almr

C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1511431671.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]

,NU_NOTIFIC,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,...,DT_TRANSRM,DT_TRANSRS,DT_TRANSSE,NU_LOTE_V,NU_LOTE_H,CS_FLXRET,FLXRECEBI,IDENT_MICR,MIGRADO_W,ID_CNS_SUS_HASHED
2,5082,2,A90,2016-03-25,201612,2016,29,293250,1385.0,2800527.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,e0f037bc45eeea73df919230256055724a0bc45b990d62...
5,22144,2,A90,2016-06-30,201626,2016,29,290460,1398.0,5075076.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
6,501,2,A90,2016-03-07,201610,2016,29,291560,1388.0,2414155.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
9,12379,2,A90,2016-01-08,201601,2016,29,291810,1393.0,2483114.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,56ba9de049836e4fa21d8a918fd7d8a6a9e69b23d5b64a...
10,2564,2,A90,2016-01-05,201601,2016,29,290560,1385.0,2771195.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,246037760bf67d1c246b8dd02298b9487c7b9b5f87f6c3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615867,1192024,2,A90,2024-02-21,202408,2024,29,292180,1398.0,2557088.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,a089fe3388d4442a5fa5e7af093309bdbbe37ee4b994b9...
615868,160858,2,A90,2024-03-03,202410,2024,29,290320,1403.0,2659069.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,0594aea8d62c0773c69b88ef616f567697270072351d82...
615869,16943,2,A90,2024-02-29,202409,2024,29,291640,1398.0,3791378.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,e98869669baa7aa8bf45ea57231a0abe0dd343361ec04d...
615870,374884,2,A90,2024-02-07,202406,2024,29,292740,1380.0,2389746.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
615873,29,2,A90,2024-03-01,202409,2024,29,292550,1388.0,7126816.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,87eaab98ce59a89ded63e587cb418249e7e6ac64b146c2...

In [21]:
def grav_condicional(df):
    # Condi√ß√µes para os campos obrigat√≥rios
    mandatory_conditions = (df['CLASSI_FIN'] == 12) & (df['CRITERIO'].isin([1, 2]))

    # Lista de campos a serem verificados
    fields = [
        'GRAV_PULSO', 'GRAV_CONV', 'GRAV_ENCH', 'GRAV_INSUF', 'GRAV_TAQUI', 
        'GRAV_EXTRE', 'GRAV_HIPOT', 'GRAV_HEMAT', 'GRAV_MELEN', 'GRAV_METRO', 
        'GRAV_SANG', 'GRAV_AST', 'GRAV_MIOC', 'GRAV_CONSC', 'GRAV_ORGAO', 'DT_GRAV'
    ]

    for field in fields:
        # Remover linhas onde o campo √© obrigat√≥rio mas est√° nulo
        df = df[~(mandatory_conditions & df[field].isna())]
        # Remover linhas onde o campo est√° preenchido mas a condi√ß√£o n√£o √© satisfeita
        df = df[~((~mandatory_conditions) & df[field].notna())]

    return df

In [22]:
df_grav = grav_condicional(df_almr)
df_grav

C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:14: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(mandatory_conditions & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1569727345.py:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~mandatory_conditions) & df[field].notna())]

,NU_NOTIFIC,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,...,DT_TRANSRM,DT_TRANSRS,DT_TRANSSE,NU_LOTE_V,NU_LOTE_H,CS_FLXRET,FLXRECEBI,IDENT_MICR,MIGRADO_W,ID_CNS_SUS_HASHED
2,5082,2,A90,2016-03-25,201612,2016,29,293250,1385.0,2800527.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,e0f037bc45eeea73df919230256055724a0bc45b990d62...
5,22144,2,A90,2016-06-30,201626,2016,29,290460,1398.0,5075076.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
6,501,2,A90,2016-03-07,201610,2016,29,291560,1388.0,2414155.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
9,12379,2,A90,2016-01-08,201601,2016,29,291810,1393.0,2483114.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,56ba9de049836e4fa21d8a918fd7d8a6a9e69b23d5b64a...
10,2564,2,A90,2016-01-05,201601,2016,29,290560,1385.0,2771195.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.0,NaN,246037760bf67d1c246b8dd02298b9487c7b9b5f87f6c3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615867,1192024,2,A90,2024-02-21,202408,2024,29,292180,1398.0,2557088.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,a089fe3388d4442a5fa5e7af093309bdbbe37ee4b994b9...
615868,160858,2,A90,2024-03-03,202410,2024,29,290320,1403.0,2659069.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,0594aea8d62c0773c69b88ef616f567697270072351d82...
615869,16943,2,A90,2024-02-29,202409,2024,29,291640,1398.0,3791378.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,e98869669baa7aa8bf45ea57231a0abe0dd343361ec04d...
615870,374884,2,A90,2024-02-07,202406,2024,29,292740,1380.0,2389746.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,9b2d5b4678781e53038e91ea5324530a03f27dc1d0e5f6...
615873,29,2,A90,2024-03-01,202409,2024,29,292550,1388.0,7126816.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,4.0,NaN,87eaab98ce59a89ded63e587cb418249e7e6ac64b146c2...

In [23]:
df_almr['DT_CHIK_S1']

2         NaN
5         NaN
6         NaN
9         NaN
10        NaN
         ...
615867    NaN
615868    NaN
615869    NaN
615870    NaN
615873    NaN
Name: DT_CHIK_S1, Length: 535203, dtype: object

In [24]:
# 35 - Exame sorol√≥gico (IgM) Chikungunya Soro 1 Data da Coleta 
# DT_CHIK_S1: Campo Essencial
# DT_CHIK_S1 >= DT_ALRM
# Habilitado apenas se campo ‚ÄòID_AGRAVO‚Äô = 2

df_grav['DT_CHIK_S1'] = pd.to_datetime(df_grav['DT_CHIK_S1'], errors='coerce')
df_grav['DT_ALRM'] = pd.to_datetime(df_grav['DT_ALRM'], errors='coerce')

# Condi√ß√µes para os campos obrigat√≥rios
chik_condition = (df_grav['ID_AGRAVO'] == 2)

# Remover linhas onde DT_CHIK_S1 √© nulo ou menor que DT_ALRM quando ID_AGRAVO √© 2

# Remover linhas onde DT_CHIK_S1 √© nulo ou menor que DT_ALRM quando ID_AGRAVO √© 2
df_grav = df_grav[~((chik_condition & df_grav['DT_CHIK_S1'].isna()) | (chik_condition & (df_grav['DT_CHIK_S1'] < df_grav['DT_ALRM'])))]

# Remover linhas onde DT_CHIK_S1 est√° preenchida mas ID_AGRAVO √© diferente de 2
df_chiks1 = df_grav[~((~chik_condition) & df_grav['DT_CHIK_S1'].notna())]

In [25]:
# 36 - Exame sorol√≥gico (IgM) Chikungunya Soro 2 Data da Coleta 
# DT_CHIK_S2: Campo Essencial 
# DT_CHIK_S2 >= DT_CHIK_S1 
# Habilitado apenas se campo ‚ÄòID_AGRAVO‚Äô = 2


df_chiks1['DT_CHIK_S2'] = pd.to_datetime(df_chiks1['DT_CHIK_S2'], errors='coerce')

# Condi√ß√µes para os campos obrigat√≥rios
chik_condition = (df_chiks1['ID_AGRAVO'] == 2)

# Remover linhas onde DT_CHIK_S2 √© nulo ou menor que DT_CHIK_S1 quando ID_AGRAVO √© 2
df_chiks1 = df_chiks1[~((chik_condition & df_chiks1['DT_CHIK_S2'].isna()) | (chik_condition & (df_chiks1['DT_CHIK_S2'] < df_chiks1['DT_CHIK_S1'])))]

# Remover linhas onde DT_CHIK_S2 est√° preenchida mas ID_AGRAVO √© diferente de 2
df_chiks2 = df_chiks1[~((~chik_condition) & df_chiks1['DT_CHIK_S2'].notna())]

C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2193479459.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_chiks1['DT_CHIK_S2'] = pd.to_datetime(df_chiks1['DT_CHIK_S2'], errors='coerce')

In [26]:
def data_unabled(df):
    # Converter colunas de data para o formato datetime
    df['DT_PRNT'] = pd.to_datetime(df['DT_PRNT'], errors='coerce')

    # Condi√ß√µes para os campos obrigat√≥rios
    chik_condition = (df['ID_AGRAVO'] == 2)

    # Lista de campos a serem verificados
    fields_to_check = ['DT_PRNT', 'RES_CHIKS1', 'RES_CHIKS2', 'RESUL_PRNT']

    for field in fields_to_check:
        # Remover linhas onde o campo √© obrigat√≥rio mas est√° nulo
        df = df[~(chik_condition & df[field].isna())]
        # Remover linhas onde o campo est√° preenchido mas a condi√ß√£o n√£o √© satisfeita
        df = df[~((~chik_condition) & df[field].notna())]

    return df

df_unabled = data_unabled(df_chiks2)

C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1005201360.py:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(chik_condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1005201360.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~chik_condition) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1005201360.py:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(chik_condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1005201360.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~chik_condition) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1005201360.py:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(chik_condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\1005201360.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~chik_condition) & df[field].notna())]

In [27]:
def idagravo_abled(df):

    # Condi√ß√µes para os campos obrigat√≥rios
    chik_condition = (df['ID_AGRAVO'] == 2)
    dengue_condition = (df['ID_AGRAVO'] == 1)

    # Lista de campos a serem verificados e suas condi√ß√µes
    fields_conditions = [
        ('DT_PRNT', chik_condition),
        ('RES_CHIKS1', chik_condition),
        ('RES_CHIKS2', chik_condition),
        ('RESUL_PRNT', chik_condition),
        ('DT_SORO', dengue_condition & (df['DT_SORO'] >= df['DT_ALRM'])),
        ('RESUL_SORO', dengue_condition),
        ('DT_NS1', dengue_condition & (df['DT_NS1'] >= df['DT_ALRM'])),
        ('RESUL_NS1', dengue_condition),
        ('HISTOPA_N', dengue_condition),
        ('IMUNOH_N', dengue_condition)
    ]

    for field, condition in fields_conditions:
        # Remover linhas onde o campo √© obrigat√≥rio mas est√° nulo
        df = df[~(condition & df[field].isna())]
        # Remover linhas onde o campo est√° preenchido mas a condi√ß√£o n√£o √© satisfeita
        df = df[~((~condition) & df[field].notna())]

    return df

df_agravo = idagravo_abled(df_unabled)

C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2885228505.py:23: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2885228505.py:25: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~condition) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2885228505.py:23: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2885228505.py:25: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~condition) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2885228505.py:23: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2885228505.py:25: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~condition) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2885228505.py:23: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2885228505.py:25: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~condition) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2885228505.py:23: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\2885228505.py:25: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~condition) & df[field].notna())]

In [28]:
def data_pcr(df):
    # Converter colunas de data para o formato datetime
    df['DT_PRNT'] = pd.to_datetime(df['DT_PRNT'], errors='coerce')
    df['DT_SORO'] = pd.to_datetime(df['DT_SORO'], errors='coerce')
    df['DT_NS1'] = pd.to_datetime(df['DT_NS1'], errors='coerce')
    df['DT_ALRM'] = pd.to_datetime(df['DT_ALRM'], errors='coerce')
    df['DT_VIRAL'] = pd.to_datetime(df['DT_VIRAL'], errors='coerce')
    df['DT_PCR'] = pd.to_datetime(df['DT_PCR'], errors='coerce')

    # Condi√ß√µes para os campos obrigat√≥rios
    chik_condition = (df['ID_AGRAVO'] == 2)
    dengue_condition = (df['ID_AGRAVO'] == 1)
    viral_pcr_condition = (df['ID_AGRAVO'].isin([1, 2]))

    # Lista de campos a serem verificados e suas condi√ß√µes
    fields_conditions = [
        ('DT_PRNT', chik_condition),
        ('RES_CHIKS1', chik_condition),
        ('RES_CHIKS2', chik_condition),
        ('RESUL_PRNT', chik_condition),
        ('DT_SORO', dengue_condition & (df['DT_SORO'] >= df['DT_ALRM'])),
        ('RESUL_SORO', dengue_condition),
        ('DT_NS1', dengue_condition & (df['DT_NS1'] >= df['DT_ALRM'])),
        ('RESUL_NS1', dengue_condition),
        ('HISTOPA_N', dengue_condition),
        ('IMUNOH_N', dengue_condition),
        ('DT_VIRAL', viral_pcr_condition & (df['DT_VIRAL'] >= df['DT_ALRM'])),
        ('RESUL_VI_N', viral_pcr_condition),
        ('DT_PCR', viral_pcr_condition & (df['DT_PCR'] >= df['DT_ALRM'])),
        ('RESUL_PCR_', viral_pcr_condition)
    ]

    for field, condition in fields_conditions:
        # Remover linhas onde o campo √© obrigat√≥rio mas est√° nulo
        df = df[~(condition & df[field].isna())]
        # Remover linhas onde o campo est√° preenchido mas a condi√ß√£o n√£o √© satisfeita
        df = df[~((~condition) & df[field].notna())]

    return df

# Aplicar a fun√ß√£o de valida√ß√£o e limpeza
df_pcr = data_pcr(df_agravo)

C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\3868305181.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\3868305181.py:37: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~condition) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\3868305181.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\3868305181.py:37: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~condition) & df[field].notna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\3868305181.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~(condition & df[field].isna())]
C:\Users\n4iar\AppData\Local\Temp\ipykernel_5620\3868305181.py:37: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~((~condition) & df[field].notna())]

In [29]:
df_pcr.describe()

,NU_NOTIFIC,TP_NOT,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,SEM_PRI,SOUNDEX,...,DT_TRANSDM,DT_TRANSRM,DT_TRANSRS,DT_TRANSSE,NU_LOTE_V,NU_LOTE_H,CS_FLXRET,FLXRECEBI,IDENT_MICR,MIGRADO_W
count,2.496870e+05,249687.0,249687.000000,249687.000000,249687.000000,249687.000000,249594.000000,2.495340e+05,249687.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,249687.000000,0.0,246352.000000,0.0
mean,1.467321e+05,2.0,202157.424351,2021.398891,29.011350,291949.914028,1390.914862,4.370599e+06,202144.785904,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.305795,NaN,4.197076,NaN
std,5.435716e+05,0.0,224.809360,2.285290,0.543517,5528.848611,68.879424,2.550572e+06,476.632347,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.460744,NaN,0.756552,NaN
min,0.000000e+00,2.0,201601.000000,2016.000000,17.000000,170210.000000,1331.000000,3.500000e+01,22411.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,3.000000,NaN
25%,6.710000e+02,2.0,202009.000000,2020.000000,29.000000,291080.000000,1381.000000,2.507447e+06,202008.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,4.000000,NaN
50%,1.067400e+04,2.0,202148.000000,2021.000000,29.000000,291800.000000,1388.000000,3.039919e+06,202140.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,4.000000,NaN
75%,5.559000e+04,2.0,202409.000000,2024.000000,29.000000,292740.000000,1398.000000,6.855180e+06,202408.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,4.000000,NaN
max,9.994664e+06,2.0,202414.000000,2024.000000,53.000000,530010.000000,6124.000000,9.999396e+06,202414.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,7.000000,NaN

In [30]:
df_pcr.to_csv('result.csv')

In [31]:
# X = df_grav.drop(columns=['CLASSI_FIN'])
# y = df_grav['CLASSI_FIN']

# X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y, test_size=0.2, random_state=42)
# X_train, X_val, y_train, y_val = train_test_split(X_train,y_train, stratify=y_train, test_size=0.25, random_state=42)

##Obrigat√≥rios

47
SOROTIPO: Obrigat√≥rio Se campo 'RESUL_VI_N' ou campo 'RESUL_PCR_'= 1.
Campo desabilitado se campo 'RESUL_VI_N' e campo 'RESUL_PCR_' diferente de 1.
Habilitado apenas se campo 'ID_AGRAVO' = 1

62
CLASSI_FIN: Campo Obrigat√≥rio quando o campo 'DT_ENCERRA' estiver preenchido.
Desabilitar categoria 13 se campo 'ID_AGRAVO'= 1.
Desabilitar categorias 10, 11 e 12 se campo 'ID_AGRAVO'=2

63 - (PENDENTE)
CRITERIO: Campo Obrigat√≥rio se classifica√ß√£o preenchida Se campo 'CLASSI_FIN' = 5, pular para o campo 'EVOLUCAO', ap√≥s o preenchimento do campo 'CRITERIO' de confirma√ß√£o descarte.

64
CLINIC_CHIK: Campo Obrigat√≥rio
Se campo 'CLASSI_FIN'=13 e se campo 'CRITERIO'= 1 ou 2

66
DT_OBITO: Campo Obrigat√≥rio se 'EVOLUCAO'=2 ou 3 ou 4.
Data deve ser maior ou igual a 'DT_ALRM'.

67
DT_ENCERRA: Campo Obrigat√≥rio quando campo 'CLASSI_FIN' estiver preenchido E o campo 'CRITERIO' for diferente de 3.
Campo desabilitado se o campo 'CRITERIO' for igual a 3.

68- Dengue com sinais de alarme (Hipotens√£o)
ALRM_HIPOT: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 11 e campo 'CRITERIO'= 1 ou 2
Campo habilitado tamb√©m se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 11 e 12

68- Dengue com sinais de alarme (Queda abrupta de plaquetas)
ALRM_PLAQ: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 11 e campo 'CRITERIO'=1 ou 2
Campo habilitado tamb√©m se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2.
Desabilitado se campo 'CLASSI_FIN' for diferente de 11 e 12.

68- Dengue com sinais de alarme (V√¥mitos persistentes)
ALRM_VOM: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 11 e campo 'CRITERIO'=1 ou 2
Campo habilitado tamb√©m se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 11 e 12

68- Dengue com sinais de alarme (Dor abdominal)
ALRM_ABDOM: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 11 e campo 'CRITERIO'=1 ou 2
Campo habilitado tamb√©m se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 11 e 12

68- Dengue com sinais de alarme (Letargia ou irritabilidade)
ALRM_LETAR: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 11 e campo 'CRITERIO'=1 ou 2
Campo habilitado tamb√©m se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 11 e 12

68- Dengue com sinais de alarme (Sangramento de mucosa/outras hemorragias)
ALRM_SANG: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 11 e campo 'CRITERIO'=1 ou 2
Campo habilitado tamb√©m se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 11 e 12

68- Dengue com sinais de alarme (Aumento hemat√≥crito)
ALRM_HEMAT: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 11 e campo 'CRITERIO'=1 ou 2
Campo habilitado tamb√©m se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 11 e 12

68- Dengue com sinais de alarme (Hepatomegalia)
ALRM_HEPAT: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 11 e campo 'CRITERIO'=1 ou 2
Campo habilitado tamb√©m se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 11 e 12

68- Dengue com sinais de alarme (Ac√∫mulo de l√≠quidos)
ALRM_LIQ: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 11 e campo 'CRITERIO'=1 ou 2
Campo habilitado tamb√©m se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 11 e 12

69
DT_ALRM: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 11 e campo 'CRITERIO'=1 ou 2
Campo habilitado tamb√©m se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 11 e 12

70- Dengue grave (Pulso d√©bil ou indect√°vel)
GRAV_PULSO: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (PA convergente)
GRAV_PULSO: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Pulso d√©bil ou indect√°vel)
GRAV_CONV: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Tempo de enchimento capilar)
GRAV_ENCH: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Ac√∫mulo de l√≠quidos com insufici√™ncia respirat√≥ria)
GRAV_INSUF: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Taquicardia)
GRAV_TAQUI: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Extremidade frias)
GRAV_EXTRE: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Hipotens√£o arterial em fase tardia)
GRAV_HIPOT: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Hemat√™mese)
GRAV_HEMAT: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Melena)
GRAV_MELEN: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Metrorragia volumosa)
GRAV_METRO: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Sangramento do SNC)
GRAV_SANG: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (AST/ALT >1 .000)
GRAV_AST: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Miocardite)
GRAV_MIOC: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Altera√ß√£o da consci√™ncia)
GRAV_CONSC: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

70- Dengue grave (Outros √≥rg√£os)
GRAV_ORGAO: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12

71- Dengue grave
Data de in√≠cio dos sintomas
DT_GRAV: Campo obrigat√≥rio
Se campo 'CLASSI_FIN' = 12 e campo 'CRITERIO'=1 ou 2
Desabilitado se campo 'CLASSI_FIN' for diferente de 12